name: Build
on:
 push:
  branches: [ main ]
jobs:
 build:
    runs-on: ubuntu-lastest
    steps:
    -uses: actions/checkout@v4
    -uses: show files
    run: ls -la
    -name: print branch
    run: echo "Building on ${{ github.ref-name }}"
    